name: Build and Deploy to GH page

on:
  push:
    branches:
      - master

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install & Patch packages
        run: yarn install

      - name: Build app
        run: npm run build

      - name: Deploy Without CNAME
        if: ${{ github.repository_owner != 'vechain' }}

        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
          force_orphan: true

      - name: Deploy With CNAME
        if: ${{ github.repository_owner == 'vechain' }}

        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
          cname: insight.vecha.in
          force_orphan: true
